version: '3.8'
services:
  backendapp:
    container_name: backendapp
    image: frongfrank17/ctv-pr:v.deploy1amd64
    restart: always
    environment:
      DB: DBCTC
      URL_DB: <IP-HOST>
      PORT_DB: 3333
      DB_USER: "root"
      DB_PASSWORD: "P@ssw0rd"